//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class competencies_detall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public competencies_detall()
        {
            this.rubriques = new HashSet<rubrique>();
            this.usuaris_has_competencies_detall = new HashSet<usuaris_has_competencies_detall>();
        }
    
        public int id { get; set; }
        public string codi { get; set; }
        public string nom { get; set; }
        public int competencies_id { get; set; }
    
        public virtual competetency competetency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rubrique> rubriques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuaris_has_competencies_detall> usuaris_has_competencies_detall { get; set; }
    }
}
