//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class competetency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public competetency()
        {
            this.competencies_detall = new HashSet<competencies_detall>();
        }
    
        public int id { get; set; }
        public string codi { get; set; }
        public string nom { get; set; }
        public string descripcio { get; set; }
        public int moduls_id { get; set; }
        public bool actiu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<competencies_detall> competencies_detall { get; set; }
        public virtual modul modul { get; set; }
    }
}
