//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public curso()
        {
            this.moduls_has_cursos = new HashSet<moduls_has_cursos>();
        }
    
        public int id { get; set; }
        public string sigles { get; set; }
        public string nom { get; set; }
        public int cicles_id { get; set; }
        public bool actiu { get; set; }
    
        public virtual cicle cicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moduls_has_cursos> moduls_has_cursos { get; set; }
    }
}
