//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class abpEntities2 : DbContext
    {
        public abpEntities2()
            : base("name=abpEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cicle> cicles { get; set; }
        public virtual DbSet<competencies_detall> competencies_detall { get; set; }
        public virtual DbSet<competetency> competetencies { get; set; }
        public virtual DbSet<curso> cursos { get; set; }
        public virtual DbSet<modul> moduls { get; set; }
        public virtual DbSet<moduls_has_cursos> moduls_has_cursos { get; set; }
        public virtual DbSet<moduls_has_professors> moduls_has_professors { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<rubrique> rubriques { get; set; }
        public virtual DbSet<usuari> usuaris { get; set; }
        public virtual DbSet<usuaris_has_competencies_detall> usuaris_has_competencies_detall { get; set; }
    }
}
