//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moduls_has_professors
    {
        public int moduls_id { get; set; }
        public int usuaris_id { get; set; }
        public int curs_academic_id { get; set; }
    
        public virtual modul modul { get; set; }
        public virtual usuari usuari { get; set; }
    }
}
