//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubrique
    {
        public int id { get; set; }
        public string descripcio { get; set; }
        public bool actiu { get; set; }
        public int nivell { get; set; }
        public int competetencies_detall_id { get; set; }
    
        public virtual competencies_detall competencies_detall { get; set; }
    }
}
