//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuaris_has_competencies_detall
    {
        public int usauris_id { get; set; }
        public int competencies_detall_id { get; set; }
        public int curs_academic_id { get; set; }
        public Nullable<int> nivell { get; set; }
    
        public virtual competencies_detall competencies_detall { get; set; }
        public virtual usuari usuari { get; set; }
    }
}
