//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationM06_04_01ProgramarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuari()
        {
            this.moduls_has_professors = new HashSet<moduls_has_professors>();
            this.usuaris_has_competencies_detall = new HashSet<usuaris_has_competencies_detall>();
        }
    
        public int id { get; set; }
        public string correu { get; set; }
        public string nom { get; set; }
        public string cognoms { get; set; }
        public string contrasenya { get; set; }
        public int rols_id { get; set; }
        public bool actiu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moduls_has_professors> moduls_has_professors { get; set; }
        public virtual rol rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuaris_has_competencies_detall> usuaris_has_competencies_detall { get; set; }
    }
}
